# docs here: https://squidfunk.github.io/mkdocs-material/

site_name: Energizer
site_url: https://pietrolesci.github.io/energizer
repo_url: https://github.com/pietrolesci/energizer
repo_name: pietrolesci/energizer
edit_uri: tree/main/docs

nav:
  - Home: index.md
  - Get started: 
    - get-started/index.md
    - Installation: get-started/installation.md
    - Energizer in 2 minutes: get-started/energizer-in-2.md
    - Implement a query strategy from scratch: get-started/implement-new-strategies.ipynb
  - Examples:
    - Simple CNN on MNIST: examples/cnn-mnist.ipynb
    - BERT on AG-News: examples/bert-agnews.ipynb
  - API Reference:
    - Trainer: api/trainer.md
    - Query strategies: api/query_strategies.md
    - Acquisition function: api/acquisition_functions.md
  - Contributing: contributing.md
  - Changelog: changelog.md

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  icon:
    logo: material/book-education-outline
    repo: fontawesome/brands/github
  font:
    text: Fira Sans Condensed
    code: JetBrains Mono

  #logo: assets/logo.png
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.tabs.link
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.superfences
  - tables
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify

plugins:
  - tags
  - include-markdown
  - mknotebooks:
      binder: true
      binder_service_name: "gh"
      binder_branch: "main"
      binder_ui: "lab"
  - git-revision-date-localized:
      enable_creation_date: true
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: false
            heading_level: 3

extra:
  version:
    provider: mike
    default: stable

  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pietro_lesci
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pietrolesci
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/pietrolesci/
      name: Github
    - icon: material/email
      link: "mailto:pietrolesci@outlook.com"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2022 - Pietro Lesci
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
