[tool]
[tool.poetry]
name = "energizer"
version = "0.1.0"
homepage = "https://github.com/pietrolesci/energizer"
description = "An active learning library for PyTorch based on Pytorch-Lightning."
authors = ["Pietro Lesci <pietrolesci@outlook.com>"]
readme = "README.md"
license =  "MIT"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
]
packages = [
    { include = "energizer" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
black = "^22.6.0"
isort  = "^5.10.1"
flake8 = "^3"
flake8-docstrings = { version = "^1.6.0", optional = true }
pytest  = { version = "^6.2.4", optional = true}
pytest-cov  = { version = "^2.12.0", optional = true}
tox  = { version = "^3.20.1", optional = true}
pre-commit = {version = "^2.12.0", optional = true}
virtualenv  = { version = "^20.2.2", optional = true}
pip  = { version = "^20.3.1", optional = true}
twine  = { version = "^3.3.0", optional = true}
bump2version = {version = "^1.0.1", optional = true}
toml = "^0.10.2"
mkdocs-include-markdown-plugin  = { version = "^1.0.0", optional = true}
mkdocs-material  = { version = "^6.1.7", optional = true}
mkdocstrings  = { version = "^0.15.2", optional = true}
mkdocs-material-extensions  = { version = "^1.0.1", optional = true}
mkdocs-autorefs = {version = "^0.2.1", optional = true}
transformers = "^4.21.1"
torch = "^1.12.0"
pytorch-lightning = "^1.7.0"
datasets = "^2.1.0"
ipykernel = "^6.13.0"
ipywidgets = "^7.7.0"
rich = "^12.3.0"
nbqa = "^1.4.0"
mypy = "^0.971"
mkdocs = "^1.3.1"
matplotlib = "^3.5.3"
sentence-transformers = "^2.2.2"
torchvision = "^0.13.1"
colorlog = "^6.6.0"
faiss-gpu = "^1.7.2"

[tool.poetry.extras]
test = [
    "black",
    "isort",
    "nbqa",
    "mypy",
    "flake8",
    "flake8-docstrings",
    "pytest",
    "pytest-cov",
    "types-pyyaml",
    ]

dev = ["tox", "pre-commit", "virtualenv", "pip", "twine", "toml", "bump2version"]

doc = [
    "mkdocs",
    "mkdocs-include-markdown-plugin",
    "mkdocs-material",
    "mkdocstrings",
    "mkdocs-material-extension",
    "mkdocs-autorefs"
    ]

vision = ["torchvision"]
text = ["transformers"]

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = true
# you can skip files as below
#skip_glob = docs/conf.py

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
